### ISSUE TITLE
This element does not work on the same page as a google-map element

### ISSUE THREAD

**Issue by rbjarnason** [GoogleWebComponents/google-streetview-pano#15] opened 2015-09-12 23:32 UTC
I get errors like:
Uncaught TypeError: m[md].maps.Load is not a function
You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

Any hints how best to fix?

**Comment by rbjarnason** [comment] 2015-09-14 17:08
@justinfagnani @garlicnation

**Comment by rbjarnason** [comment] 2015-09-23 10:18
At the Polymer Code Labs there was suspicion that this problem originates in the iron-jsonp-library, causing the Google Maps API to be loaded twice.

**Comment by rbjarnason** [comment] 2015-09-29 10:41
@justinfagnani @garlicnation Any pointers for me, if I start looking at the issue myself?

**Comment by addyosmani** [comment] 2015-09-29 10:59
Do you have a code sample that reproduces the `Uncaught TypeError: m[md].maps.Load is not a function` exception you're seeing?

**Comment by rbjarnason** [comment] 2015-09-29 11:03
Here is a link that reproduces the error live:
http://www.your-priorities-preview.org/#!/group/2

And here is a link to the element that can show either Google maps or Google StreetView:
https://github.com/rbjarnason/your-priorities-app/blob/master/client_app/elements/yp-idea/yp-idea-cover-media.html

**Comment by rbjarnason** [comment] 2015-09-29 11:10
Seems to be showing "You have included the Google Maps API multiple times on this page." all the time now but the "Uncaught TypeError: m[md].maps.Load is not a function" does show up sometimes, we looked at this at the Polymer Code Labs in Amsterdam and looked like a timing issue what error would show...

**Comment by garlicnation** [comment] 2015-09-29 15:14
The problem is the "libraries" field of the google-maps-api element. google-streetview-pano defaults to "places", and google-map defaults to "". This causes iron-jsonp-library to treat google-map as a separate library and causes the error.

 The "libraries" object may need to be a singleton, and can only be configured once per application. Additionally, the google api wrapper should refuse to load any library a second time.

**Comment by rbjarnason** [comment] 2015-09-29 15:41
I tried setting google-maps libraries to default to 'places' to test this - and works better and I can see maps and streetview on the same page. But there is still an issue, if I move between iron-pages with streetview being redrawn I get the error in this screenshot.  Maybe I should file that separately or is this connected? Seem to be that you can't load GoogleStreetViewPano elements twice in the same iron-pages "session". 

![streetviewpanobug](https://cloud.githubusercontent.com/assets/43699/10169427/88a5ee5c-66c0-11e5-9ba2-ee02429bfbed.png)

**Comment by ebidel** [comment] 2015-09-29 16:36
That's right. A [recent change](https://github.com/GoogleWebComponents/google-map/commit/82e4e5a5698958aaa063fe99aa5e1e5f0d02775c) of `google-map` changed the default `libraries="places"` to `libraries=""` because most people will only be using `google-map` by itself. There was no reason to load the places library for all users when they never needed it.

@garlicnation the problem with not loading the library twice is that `iron-jsonp-library` doesn't know what URLs you give it. So using a different maps component that requires different set of libraries will cause this error. This is a fundamental flaw with how the Maps API loads modules. @brendankenny explained it to me once, and I cried. Our solution was to require users to specify the same `libraries` value on all maps components that are loaded. Do you think there's a cleaner way with iron-meta or something?

@rbjarnason that error looks unrelated. Can you file a separate issue?

**Comment by ebidel** [comment] 2015-09-29 16:39
Added a note to the docs: https://github.com/GoogleWebComponents/google-streetview-pano/commit/2b1135773f7dbf2cedb756e4f9cc412b65b76aea

**Comment by rbjarnason** [comment] 2015-09-29 17:22
Thanks @ebidel I have researched this a bit more and filed a new issue here https://github.com/GoogleWebComponents/google-streetview-pano/issues/16 for the failure on second use with iron-pages.

**Comment by rbjarnason** [comment] 2015-09-29 17:56
As we now have a workaround I won't spend more time on this and will leave it up to you guys to find a solution for this in due time.  Thanks for your help! :)

**Comment by ebidel** [comment] 2015-09-30 17:04
Thanks. I'm going to close this issue then.

**Closed by ebidel** 2015-09-30 17:04 UTC
Labels: bug
